packages:
  -
  # all packages in direct subdirs of packages/
  # - 'ragged'
  # - 'documentation'
  # # all packages in subdirs of components/
  # - 'examples/*'
  # # # exclude packages that are inside test directories
  # # - '!**/test/**'
  # # Just a scratch project
  # - 'scratch'
  # # End to end testing
  # - 'e2e'
